spring:
  data:
    mongodb:
      host: 192.168.100.28
      port: 27017
      database: doushu
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

  rabbitmq:
    host: 192.168.100.28
    port: 5672
    username: douyin
    password: douyin
    virtual-host: douyin
    publisher-returns: true  #支持消息发送失败返回队列
    publisher-confirm-type: correlated #消息发送到交换机确认机制，是否确认回调
    #配置监听
    listener:
      simple:
        acknowledge-mode: manual #设置消费端手动 ack   none不确认  auto自动确认  manual手动确认
        concurrency: 1   #消费者最小数量
        max-concurrency: 3 #消费之最大数量
        #开启消费者重试机制(为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息)
        retry:
          enabled: true
          max-attempts: 3 #重试次数5
          initial-interval: 1000  #重试时间间隔
        #重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
        default-requeue-rejected: true
        #在单个请求中处理的消息个数，他应该大于等于事务数量(unack的最大数量)
        prefetch: 2
