server:
  port: 8010
  servlet:
    context-path: /v1
spring:
  application:
    name: sass
  # jackson时间格式化
  jackson:
#   返回序列化时间戳
#   serialization:
#   write-dates-as-timestamps: true
#   返回序列化指定格式
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
config:
  jwt:
    secret: abcdefg1234567  # 加密密钥
    expire: 3600  # token有效时长，这里表示3600秒，表示一个小时
    header: token  # header 名称
    ignore-urls:
      - /error
      - /swagger-resources/**
      - /doc.html
      - /v2/api-docs
      - /webjars/**
