# ??????user????UUid??SecurityProperties.User????????cookie?JSESSIONID=xxx??????????cookie???????
spring:
  security:
    user:
      name: admin
      password: 123456
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
