
wechat:
  appid: wx21275befc3289eaf
  secret: 74f4c96bccd72fc1ce2c85204cdca465
  grant_type: authorization_code


wx:
  wxNotifyUrl:
    # 注意：这里实际应该配置外网可以直接访问的地址
    refund: https://你的域名/wx-notify/refund
    pay: https://你的域名/wx-notify/pay
  pay:
    #精选小程序
    jx:
      #微信公众号或者小程序等的appid
      appId: xxxxxxx
      secret: kkkkkk
      #微信支付商户号
      mchId: yyyyyyy
      #微信支付商户密钥
      mchKey: zzzzzzz
      subAppId: #服务商模式下的子商户公众账号ID（可选）
      subMchId: #服务商模式下的子商户号
      # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
      keyPath: classpath:apiclient_cert.p12




user:
  server:
    url: http://127.0.0.1:8070
